name: Wheels

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheels
        env:
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python -m pytest -q
        run: python -m cibuildwheel --output-dir wheelhouse
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ runner.os }}
          path: wheelhouse/*

